### ISSUE TITLE
awesome_clicker : Always show : web.assets_web.min.js:1139 Component 'ClickerValue' does not have a static props description

### ISSUE THREAD

**Issue by DHoper** [odoo/tutorials#24] opened 2024-01-04 07:14 UTC
Always show : web.assets_web.min.js:1139 Component 'ClickerValue' does not have a static props description Warning

And clicker_model's toJSON() method is defined but never to use， so if we use the original solution like :
```
 start(env, services) {
        const localState = migrate(JSON.parse(browser.localStorage.getItem("clickerState")));
        const clickerModel = localState ? ClickerModel.fromJSON(localState): new ClickerModel();

        setInterval(() => {
            browser.localStorage.setItem("clickerState", JSON.stringify(clickerModel))
        }, 10000);
        ......
```
will throw an error，seem like because the [this.bus] is not be delete and will conflict with migrationstep(step 20)?

**Comment by fdardenne** [comment] 2024-01-11 08:47
Hello,
`And clicker_model's toJSON() method is defined but never to use`.

The `toJSON` method is called when invoking `JSON.stringify(clickerModel)` so it is used. I can't reproduce the crash, the bus is defined on my end.

For the static props warning, it is now fixed.

Thank you.

**Closed by fdardenne** 2024-01-11 08:47 UTC
